### PR TITLE
Fixing data loading, data availability and partial loading

### PR DESCRIPTION
**Pull request by Abhra1992**
Adding 3 fixes in the pipeline:
- Partials can now be accessed using any of the file extensions `.{html,hbs,handlebars}`.
- Site-wide data from `data/` folder made available in templates.
- Fix overwriting of data objects when there are multiple data files.

### CODE REVIEW

**Comment by gakimball** [comment]
Thanks for catching these oversights. The only change I'm going to make after I pull this in is putting external data files at the root of the Handlebars context, instead of being inside a `data` variable. That will be easier for people to reason about.

**Comment by Abhra1992** [comment]
Just a suggestion, don't you think there should be a distinction between site-wide data (in `data/` folder), handlebars helpers (in `helpers/` folder) and frontmatter data (from top of page). They all look the same in a `.hbs` template, and there might be conflicts if there are two such artifacts of the same name. (I am not sure what happens in this case).
IMO, you could have something like `{{xyz}}` for helpers, `{{data.xyz}}` for data, and `{{fm.xyz}}` for frontmatter.

**Comment by gakimball** [comment]
Definitely makes sense, but this plugin is specifically designed for small projects, which is why we're okay with the potential namespacing issue. There are only six "reserved" keywords right now that we've added (four helpers and two variables), and most of them have fairly specific names.

For large static sites, tools like Assemble, Jekyll, Metalsmith, etc. are going to be more appropriate.

**Comment by Abhra1992** [comment]
Right that makes sense. I definitely agree that this model is much simpler.

**Pull request merged**
