### PR TITLE
update handlebars

### PR DESCRIPTION
**Pull request by timaschew**

### CODE REVIEW

**Comment by gakimball** [comment]
Need to test this against the Foundation documentation first—I thought I came across some issue with Handlebars 4 and raw helpers (`{{{{ raw }}}}`), but that could have been something else.

I'll get back to you in a bit!

**Comment by gakimball** [comment]
Alright, we're solid. I'll publish a new version of Panini with this change in a sec.

**Comment by timaschew** [comment]
Great!

**Comment by eMerzh** [comment]
it's me or the helper is not loaded ?

**Pull request merged**
