### PR TITLE
Add support for subdirectory partial structure

### PR DESCRIPTION
**Pull request by jefsnare**
Just check if the last directory in the directory array of the file is equal to 'partials', if not prepend the folder name of the partial.
This is not recursive, one level only.

### CODE REVIEW

**Comment by thexebolud** [comment]
The partial folder can be customized and would be broken by this change.

**Comment by jefsnare** [comment]
@thexebolud Good to know, should I apply a fix for that in this PR?

**Comment by gakimball** [comment]
Is the use-case for this to get partial names that include the file's containing folder?

Like you have `src/partials/sub/partial.html` and it can be included as `{{> sub/partial }}` instead of `{{> partial }}`.

We'll do this in a 2.0 version of Panini, because it's a breaking change. See #22

**Comment by thexebolud** [comment]
I have a fork nyself with this problem solved.

________________________________

**Comment by thexebolud** [comment]
This is the final file for me. @jefsnare , you could update it like this on your PR.
@gakimball I am currently using this version of the file, no other changes and everything works fine. Por big project partial subfolders is a must.

```
var fs    = require('fs');
var path  = require('path');
var utils = require('./utils');

/**
 * Looks for files with .html, .hbs, or .handlebars extensions within the given directory, and adds them as Handlebars partials matching the name of the file.
 * @param {string} dir - Folder to check for partials.
 */
module.exports = function (dir) {
  var full_dir_path = (process.cwd() + '/' + dir).replace(/\\/g, '/') + (dir.indexOf('/', dir.length - 1) == -1 ? '/' : ''),
    partials = utils.loadFiles(dir, '**/*.{html,hbs,handlebars}');

  for (var i in partials) {
    var ext = path.extname(partials[i]),
      file = fs.readFileSync(partials[i]),
      name = partials[i].substring(full_dir_path.length, partials[i].length - ext.length);

    this.Handlebars.registerPartial(name, file.toString() + '\n');
  }
}
```

**Comment by jefsnare** [comment]
@gakimball Yes, that's correct. Please close this PR if this is fixed in 2.0. Thank you!

**Comment by gakimball** [comment]
@jefsnare 👍  Follow along at home: <https://github.com/zurb/panini/tree/v2.0>

**Pull request closed without merging**
