### PR TITLE
Update render() - replace ._extend with deep merge; adjust order of merging data

### PR DESCRIPTION
**Pull request by avr**
I'm not sure if this is useful.  I was having some issues when using `gulp-nav` with content/settings not coming through.  This gives the page front matter precedence.

### CODE REVIEW

**Comment by gakimball** [comment]
So it goes Front Matter, then Vinyl metadata, then page/layout/root?

Those last three are important because they need to be in every template, but since they get extend'd in last that means they always take precedence, right?

**Comment by avr** [comment]
Actually - I think it's reversed.

Root first (`this.data`), Vinyl second (`file.data`), and Front Matter (`page.attributes`) last.

I may have messed it up - but that was my intention.  Hopefully to allow for the page template to have final say.

My use case is default attributes for the site with local overrides at the page level.  Feel free to let me know if I've missed or clobbered something that needs to be there.

**Comment by gakimball** [comment]
`page`, `layout`, and `root` should be considered constants—they always need to be there.

As for Front Matter vs. Vinyl properties, I guess I'm not sure which should take precedence. It seems like both correlate to exactly one file, though, so it's not a case of a generic setting being overridden by a more specific one.

This is probably what the order should be, from most important to least important:

- `page`, `layout`, and `root`
- Page-specific data (Front Matter and Vinyl metadata)
- Global data (from external JSON/YML)

**Comment by avr** [comment]
Sorry - I was confused.  You mean the actual attributes of `page`, `layout`, and `root`.  I thought you meant data sources.

So - more like this:

```
    // Build page data with globals
    pageData = extend({}, this.data);

    // Add any data from stream plugins
    pageData = (file.data) ? extend(pageData, file.data) : pageData;

    // Add this page's front matter
    pageData = extend(pageData, page.attributes);

    // Finish by adding constants
    pageData = extend(pageData, {
      page: path.basename(file.path, '.html'),
      layout: layout,
      root: processRoot(file.path, this.options.root)
    });
```

**Comment by gakimball** [comment]
Yes, that looks right. Sorry for the confusion!

**Comment by avr** [comment]
Sounds good - I'll push that up.

I think my original hope was to have a default layout defined in global data - but that depended on attributes at the root level of `this.data` (which makes sense why you're keeping that as is).

**Comment by gakimball** [comment]
The default layout is always `default.html`.

If you're interested in implementing #26, it would be possible to more quickly define default layouts for pages by folder.

**Comment by avr** [comment]
Just rethought this.  I think the desire to have a default layout defined somewhere is a carry over from another build tool.  Panini's default is great.  Thanks.

**Pull request merged**
