### PR TITLE
Allow string|array of directories

### PR DESCRIPTION
**Pull request by avr**
This allows a string or array to be passed as an option for layouts, partials, or data.

### CODE REVIEW

**Comment by gakimball** [comment]
Thanks! :) There's a test failing related to loading data, could you look into it? I think it's because the `loadData()` function doesn't process files the same way as the partial, layout, etc. functions.

**Comment by avr** [comment]
Sorry for all the commits - I didn't quite see what was going on.  Let me know if you'd like me to squash this down.

**Comment by gakimball** [comment]
Yeah, you can squash it.

**Comment by gakimball** [comment]
Thanks!

**Pull request merged**
